### ISSUE TITLE
SocketIoClient not able to connect

### ISSUE THREAD

**Issue by davidhckh** [lucalas/StreamlabsArduinoAlerts#6]
Hi there,

today I wanted to try something using your library, but it just keeps saying "[SIoC] Disconnected!" and I can't figure out why.
I installed WebSockets, SocketIoClient and Json. My Streamlabs Socket Token should be correct too, as it worked fine a few months ago. @lucalas Could you please confirm this library is up-to-date?

Greetings!

**Comment by lucalas** [comment]
Did you solve your problem? how?
Right now I'm focused on something else and I don't have time to have a look, i'll do in the future.

**Comment by davidhckh** [comment]
Not directly. I think the problem is either related to SocketIOClient, WebSockets or me .
But luckily I found a alternative way that works for me. Now I'm pinging the Arduino from my PC, which is catching the Streamlabs alerts.

But thank you anyway and good luck on your projects!

**Comment by lucalas** [comment]
I'm glad to know that you found another way to do it.
I think the problem is inside SocketIOClient, I created an issue #2 to replace socketIOClient library using native class of WebSockets library but I had problems with the implementation.

But I hope to fix these kind of problems sooner or later.
Good luck too!
